// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xygzwjgoobrdbgwzxcwe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh5Z3p3amdvb2JyZGJnd3p4Y3dlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTczMjk0MjMsImV4cCI6MjA3MjkwNTQyM30.Cp8ftdGhtTRw6CM1DVcAEKfHBgusIOdsMHavgsCCX_E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});